version: "3"
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: notifications
    ports:
      - "5432:5432"
# pass