version: "3.5"
services:

  admin_panel:
    container_name: fake_netflix_notification_admin
    build:
      context: .
      dockerfile: dockerfiles/admin/Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: notifications
      POSTGRES_HOST: postgres
    volumes:
      - fake_netflix_notification_static:/app/static
      - fake_netflix_notification_media:/app/media

  api:
    container_name: fake_netflix_notification_api
    build:
      context: .
      dockerfile: dockerfiles/api/Dockerfile
    ports:
      - 8001:8000

  user_service:
    container_name: fake_netflix_user_service
    build:
      context: .
      dockerfile: dockerfiles/user_service/Dockerfile
    ports:
      - 8002:8002

  scheduler:
    container_name: fake_netflix_scheduler
    build:
      context: .
      dockerfile: dockerfiles/scheduler/Dockerfile
    environment:
      POSTGRES_DSN: postgres://postgres:postgres@postgres:5432/notifications
      USER_SERVICE_URL: http://user_service:8002/api/v1/
    depends_on:
      - user_service
      - postgres

  worker:
    container_name: fake_netflix_worker
    build:
      context: .
      dockerfile: dockerfiles/worker/Dockerfile
    environment:
      POSTGRES_DSN: postgres://postgres:postgres@postgres:5432/notifications
      USER_SERVICE_URL: http://user_service:8002/api/v1/
      EMAIL_SENDER_TYPE: fake
      DATA_SOURCE_TYPE: fake
    depends_on:
      - user_service
      - postgres

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: notifications
      POSTGRES_HOST: localhost
    volumes:
      - postgres_notification_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: fake_netflix_notification_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    ports:
      - 5672:5672
      - 15672:15672

  nginx:
    container_name: fake_netflix_notification_nginx
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d
      - fake_netflix_notification_static:/usr/share/nginx/www/static
      - fake_netflix_notification_media:/usr/share/nginx/www/media

volumes:
  postgres_notification_data:
  fake_netflix_notification_static:
  fake_netflix_notification_media:
