# Generated by Django 4.0 on 2022-01-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingtask',
            name='priority',
            field=models.CharField(choices=[('high', 'Высокий приоритет'), ('medium', 'Средний приоритет'), ('low', 'Низкий приоритет')], default='low', max_length=250),
        ),
        migrations.AlterField(
            model_name='mailingtask',
            name='status',
            field=models.CharField(choices=[('pending', 'В очередь на отправку'), ('in_process', 'В процессе отправки'), ('done', 'Отправлено'), ('cancelled', 'Отменено')], default='pending', max_length=250),
        ),
    ]
