# Generated by Django 4.0 on 2022-01-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_mailingtask_priority_alter_mailingtask_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='template',
            table='notification_templates',
        ),
    ]
