# Generated by Django 4.0 on 2022-01-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_template_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingtask',
            name='transport',
            field=models.CharField(choices=[('email', 'email'), ('sms', 'sms')], default='email', max_length=250),
        ),
    ]
